/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.
  To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.

  Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 * OpenAPI spec version: 1.0.0
 */
import type { BrandedFoodItemLabelNutrientsFat } from './brandedFoodItemLabelNutrientsFat';
import type { BrandedFoodItemLabelNutrientsSaturatedFat } from './brandedFoodItemLabelNutrientsSaturatedFat';
import type { BrandedFoodItemLabelNutrientsTransFat } from './brandedFoodItemLabelNutrientsTransFat';
import type { BrandedFoodItemLabelNutrientsCholesterol } from './brandedFoodItemLabelNutrientsCholesterol';
import type { BrandedFoodItemLabelNutrientsSodium } from './brandedFoodItemLabelNutrientsSodium';
import type { BrandedFoodItemLabelNutrientsCarbohydrates } from './brandedFoodItemLabelNutrientsCarbohydrates';
import type { BrandedFoodItemLabelNutrientsFiber } from './brandedFoodItemLabelNutrientsFiber';
import type { BrandedFoodItemLabelNutrientsSugars } from './brandedFoodItemLabelNutrientsSugars';
import type { BrandedFoodItemLabelNutrientsProtein } from './brandedFoodItemLabelNutrientsProtein';
import type { BrandedFoodItemLabelNutrientsCalcium } from './brandedFoodItemLabelNutrientsCalcium';
import type { BrandedFoodItemLabelNutrientsIron } from './brandedFoodItemLabelNutrientsIron';
import type { BrandedFoodItemLabelNutrientsPostassium } from './brandedFoodItemLabelNutrientsPostassium';
import type { BrandedFoodItemLabelNutrientsCalories } from './brandedFoodItemLabelNutrientsCalories';

export type BrandedFoodItemLabelNutrients = {
  fat?: BrandedFoodItemLabelNutrientsFat;
  saturatedFat?: BrandedFoodItemLabelNutrientsSaturatedFat;
  transFat?: BrandedFoodItemLabelNutrientsTransFat;
  cholesterol?: BrandedFoodItemLabelNutrientsCholesterol;
  sodium?: BrandedFoodItemLabelNutrientsSodium;
  carbohydrates?: BrandedFoodItemLabelNutrientsCarbohydrates;
  fiber?: BrandedFoodItemLabelNutrientsFiber;
  sugars?: BrandedFoodItemLabelNutrientsSugars;
  protein?: BrandedFoodItemLabelNutrientsProtein;
  calcium?: BrandedFoodItemLabelNutrientsCalcium;
  iron?: BrandedFoodItemLabelNutrientsIron;
  postassium?: BrandedFoodItemLabelNutrientsPostassium;
  calories?: BrandedFoodItemLabelNutrientsCalories;
};
