/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.
  To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.

  Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 * OpenAPI spec version: 1.0.0
 */
import type { FoodsCriteriaFormat } from './foodsCriteriaFormat';

/**
 * JSON for request body of 'foods' POST request. Retrieves a list of food items by a list of up to 20 FDC IDs. Optional format and nutrients can be specified. Invalid FDC ID's or ones that are not found are omitted and an empty set is returned if there are no matches.
 */
export interface FoodsCriteria {
  /**
   * List of multiple FDC ID's
   * @minItems 1
   * @maxItems 20
   */
  fdcIds?: number[];
  /** Optional. 'abridged' for an abridged set of elements, 'full' for all elements (default). */
  format?: FoodsCriteriaFormat;
  /**
   * Optional. List of up to 25 nutrient numbers. Only the nutrient information for the specified nutrients will be returned.  If a food does not have any matching nutrients, the food will be returned with an empty foodNutrients element.
   * @minItems 1
   * @maxItems 25
   */
  nutrients?: number[];
}
