/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.
  To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.

  Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 * OpenAPI spec version: 1.0.0
 */
import type { GetFoodsListDataTypeItem } from './getFoodsListDataTypeItem';
import type { GetFoodsListSortBy } from './getFoodsListSortBy';
import type { GetFoodsListSortOrder } from './getFoodsListSortOrder';

export type GetFoodsListParams = {
/**
 * Optional. Filter on a specific data type; specify one or more values in an array.
 */
dataType?: GetFoodsListDataTypeItem[];
/**
 * Optional. Maximum number of results to return for the current page. Default is 50.
 */
pageSize?: number;
/**
 * Optional. Page number to retrieve. The offset into the overall result set is expressed as (pageNumber * pageSize)
 */
pageNumber?: number;
/**
 * Optional. Specify one of the possible values to sort by that field. Note, dataType.keyword will be dataType and lowercaseDescription.keyword will be description in future releases.
 */
sortBy?: GetFoodsListSortBy;
/**
 * Optional. The sort direction for the results. Only applicable if sortBy is specified.
 */
sortOrder?: GetFoodsListSortOrder;
};
