/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * USDA FoodData Central API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFoodsSearch200FoodsItem } from './getFoodsSearch200FoodsItem';

export type GetFoodsSearch200 = {
  foods?: GetFoodsSearch200FoodsItem[];
};
