/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * USDA FoodData Central API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFoodFdcId200Nutrients } from './getFoodFdcId200Nutrients';

export type GetFoodFdcId200 = {
  nutrients?: GetFoodFdcId200Nutrients;
};
