/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Food Data Central API
 * The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.
  To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.

  Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)
 * OpenAPI spec version: 1.0.0
 */
import type { SearchResultFoodSearchCriteria } from './searchResultFoodSearchCriteria';
import type { SearchResultFood } from './searchResultFood';

export interface SearchResult {
  /** A copy of the criteria that were used in the search. */
  foodSearchCriteria?: SearchResultFoodSearchCriteria;
  /** The total number of foods found matching the search criteria. */
  totalHits?: number;
  /** The current page of results being returned. */
  currentPage?: number;
  /** The total number of pages found matching the search criteria. */
  totalPages?: number;
  /** The list of foods found matching the search criteria. See Food Fields below. */
  foods?: SearchResultFood[];
}
