/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * USDA FoodData Central API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type GetFoodsSearchParams = {
query: string;
};

export type GetFoodsSearch200FoodsItem = {
  fdcId?: number;
};

export type GetFoodsSearch200 = {
  foods?: GetFoodsSearch200FoodsItem[];
};

export type GetFoodFdcId200Nutrients = { [key: string]: unknown };

export type GetFoodFdcId200 = {
  nutrients?: GetFoodFdcId200Nutrients;
};

export const getUSDAFoodDataCentralAPI = () => {
/**
 * @summary Search foods by query
 */
const getFoodsSearch = <TData = AxiosResponse<GetFoodsSearch200>>(
    params: GetFoodsSearchParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/foods/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get detailed food data by fdcId
 */
const getFoodFdcId = <TData = AxiosResponse<GetFoodFdcId200>>(
    fdcId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/food/${fdcId}`,options
    );
  }

return {getFoodsSearch,getFoodFdcId}};
export type GetFoodsSearchResult = AxiosResponse<GetFoodsSearch200>
export type GetFoodFdcIdResult = AxiosResponse<GetFoodFdcId200>
